### ISSUE TITLE
Improve NEAT parameters

### ISSUE THREAD

**Issue by wmartins** [famw/SpelunkBots#8]

**Comment by martinduartemore** [comment]
Some information that I could gather about NEAT parameters:

### Traits

Traits are **NOT** functional on this version of NEAT. This means that we do not need to care about any parameters related to traits. Check these links for "proof":
- [1](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.h#L30)
- [2](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/trait.h#L32)
- [3](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/README#L30)

### Parameters

There is a lot of information about the parameters on the [`neat.h`](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/neat.h) file.

List of where the parameters are used:
- `genome.cpp`
  - [recur_only_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L1575)
  - [disjoint_coeff](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L3003)
  - [excess_coeff](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L3004)
  - [mutdiff_coeff](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L3005)
  - [linktrait_mut_sig (not being used)](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/trait.cpp#L121)
  - [nodetrait_mut_sig (not being used)](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L1089)
  - [recur_prob (not being used)](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L1765)
- `population.cpp`
  - [compat_threshold](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/population.cpp#L322)
  - [babies_stolen](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/population.cpp#L436)
  - [dropoff_age](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/population.cpp#L593)
  - [pop_size](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/population.cpp#L599)
- `species.cpp`
  - [age_significance](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L301)
  - [survival_thresh](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L324)
  - [weight_mut_power](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L448)
  - [mutate_add_link_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L505)
  - [newlink_tries](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L512)
  - [mutate_only_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L545)
  - [mutate_add_node_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L578)
  - [mutate_random_trait_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L595)
  - [mutate_link_trait_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L599)
  - [mutate_node_trait_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L603)
  - [mutate_link_weights_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L607)
  - [mutate_toggle_enable_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L611)
  - [mutate_gene_reenable_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L616)
  - [interspecies_mate_rate](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L653)
  - [mate_multipoint_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L721)
  - [mate_multipoint_avg_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L724)
  - [mate_singlepoint_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L724)
  - [mate_only_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/species.cpp#L735)
- `trait.cpp`
  - [trait_param_mut_prob](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/trait.cpp#L120)
  - [trait_mutation_power](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/trait.cpp#L121)

**Comment by martinduartemore** [comment]
### Useless Parameters
- trait_param_mut_prob
- trait_mutation_power
- linktrait_mut_sig
- nodetrait_mut_sig
- recur_prob
- mutate_random_trait_prob
- mutate_link_trait_prob
- mutate_node_trait_prob

### Useful Parameters
- weight_mut_power: how strong weights are mutated
- disjoint_coeff: compatibility between two genomes (same gene, different innovation)
- excess_coeff: compatibility between two genomes (extra genes)
- mutdiff_coeff: compatibility between two genomes (same gene and innovation, different mutation value)
- compat_threshold: compatibility threshold under which two genomes are considered the same species
- age_significance: how much a species' age matters (new species get bonus fitness) (>=1)
- survival_thresh: How many parent genomes get to reproduce (%)
- mutate_only_prob: probability of a non-mating reproduction (%)
- mutate_link_weights_prob: probability of mutating weights (%)
- mutate_toggle_enable_prob: probability of toggling a gene on/off (%)
- mutate_gene_reenable_prob: probability of reenabling a disabled gene (%)
- mutate_add_node_prob: probability of adding a node (%)
- mutate_add_link_prob: probability of adding a link (%)
- interspecies_mate_rate: probability of a non-mating reproduction  (%, lower = within same species)
- mate_multipoint_prob: no clue
- mate_multipoint_avg_prob: no clue
- mate_singlepoint_prob: no clue
- mate_only_prob: probability of mating without mutation (%, lower = only mating)
- recur_only_prob: Probability of forcing selection of ONLY links that are naturally recurrent
- pop_size: initial population size
- dropoff_age: age where species starts to be penalized
- newlink_tries: number of tries to add a new link
- babies_stolen: Number of babies to siphon off to the champions

**Comment by martinduartemore** [comment]
We could try basing our parameters around the parameters used on [**MarI/O**](http://pastebin.com/ZZmSNaHX), since the problem we are trying to solve is quite similar:
- **weight_mut_power: StepSize = 0.1 (but our equations are very different)**
- **disjoint_coeff: DeltaDisjoint = 2.0**
- excess_coeff:
- **mutdiff_coeff: DeltaWeights = 0.4**
- **compat_threshold: DeltaThreshold = 1.0**
- age_significance:
- survival_thresh:
- **mutate_only_prob: CrossoverChance = 0.75**
- **mutate_link_weights_prob: MutateConnectionsChance = 0.25**
- **mutate_toggle_enable_prob: DisableMutationChance = 0.4**
- **mutate_gene_reenable_prob: EnableMutationChance = 0.2**
- **mutate_add_node_prob: NodeMutationChance = 0.50**
- **mutate_add_link_prob: LinkMutationChance = 2.0**
- interspecies_mate_rate:
- mate_multipoint_prob:
- mate_multipoint_avg_prob:
- mate_singlepoint_prob:
- mate_only_prob:
- recur_only_prob:
- **pop_size: Population = 300**
- **dropoff_age: StaleSpecies = 15**
- newlink_tries:
- babies_stolen:

PerturbChance = 0.90 -> this option doesn't exist for us: [check here](https://github.com/famw/SpelunkBots/blob/master/DLL%20Solution/Bot/lib/NEAT/genome.cpp#L1264)

BiasMutationChance = 0.40 -> we don't have the option to add new bias nodes

**Comment by martinduartemore** [comment]
After some analysis, I think we should focus on experimenting with the following parameters:
- **weight_mut_power**: weights are modified more aggressively the higher this value is. A bigger value possibly means our bot will adapt/learn faster, but a value too high could compromise our bot's learning capabilites (I think).
- **mutate_link_weights_prob**: we need to modify weights constantly, so we should probably make NEAT emphasize this.
- **mutate_add_node_prob**: this shouldn't occur as frequently as weight modification, but should still happen oftenly.
- **mutate_add_link_prob**: same as above.
- **pop_size**: we should experiment with different population sizes, but the starting point should be at least 100. Since we are having trouble increasing the execution's speed, this value shouldn't be too high for now.
